version: "3.9"
services:
  postgres-service:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgres
      - ./dbscripts/postgres:/docker-entrypoint-initdb.d
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"